### ISSUE TITLE
Composer install errors on main branch

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az-quickstart-scaffolding#137]
## Problem/Motivation
@tadean noticed this morning that composer installs are failing in lando.

### Describe the bug
```
PHP Fatal error:  Uncaught Error: Call to undefined method Drupal\Composer\Plugin\Scaffold\ComposerScaffoldCommand::requireComposer() in /app/vendor/drupal/core-composer-scaffold/ComposerScaffoldCommand.php:51

Script @composer drupal:scaffold handling the post-update-cmd event returned with error code 255
ERROR ==> Script @composer drupal:scaffold handling the post-update-cmd event returned with error code 255 
```

### To Reproduce

1. Clone az_quickstart repo (fresh copy)
2. `lando start`
3. See errors

## Proposed resolution
This seems to be related to the version of the drupal/core-composer-scaffold package getting installed being different than the `drupal/core-recommended` package:

```
  - Installing drupal/core-composer-scaffold (10.2.0)
...
  - Installing drupal/core-recommended (10.1.7)
```

### Expected behavior
Composer install should work on a fresh clone (via lando or ddev)

**Comment by bberndt-uaz** [comment]
I am still getting this error on a fresh clone when I run `lando start` or `lando rebuild`.
