### ISSUE TITLE
PHPCS should ignore node_modules directory

### ISSUE THREAD

**Issue by jwmoore1** [az-digital/az-quickstart-scaffolding#19]
**Describe the bug**
When running phpcs, a lot of warnings show up originating in the node_modules directory, which should be ignored. 

**To Reproduce**
1. Run `lando phpcs` in main directory of az-quickstart after starting and installing with lando.

**Expected behavior**
We want phpcs to show any warnings or issues related to our code, not external libraries.

**Comment by tadean** [comment]
This issue came in with the PR on the install profile that adds node modules for the js transpilation process. Good catch @jwmoore1 !
