### ISSUE TITLE
We need to find a new solution for security checking since the one we use now has been discontinued.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az-quickstart-scaffolding#37]
Composer defines script https://github.com/az-digital/az-quickstart-scaffolding/blob/main/composer.json#L53-L56

https://github.com/sensiolabs/security-checker

github workflow set here: https://github.com/az-digital/az_quickstart/blob/main/.github/workflows/security.yml#L42

Related to https://github.com/az-digital/az-quickstart-dev/issues/8

**Comment by joeparsons** [comment]
Duplicate of az-digital/az_quickstart#504
